project_id = "iepyngyowgdiendyoqnu"

[functions.facebook-accounts]
verify_jwt = true

[functions.facebook-search]
verify_jwt = true

[functions.facebook-extract]
verify_jwt = true

[functions.facebook-publish]
verify_jwt = true

[functions.facebook-analyze]
verify_jwt = true

[functions.whatsapp-send]
verify_jwt = true

[functions.whatsapp-extract]
verify_jwt = true

[functions.whatsapp-groups]
verify_jwt = true

[functions.instagram-accounts]
verify_jwt = true

[functions.instagram-extract]
verify_jwt = true

[functions.instagram-follow]
verify_jwt = true

[functions.instagram-send]
verify_jwt = true

[functions.x-extract]
verify_jwt = true

[functions.x-publish]
verify_jwt = true

[functions.x-interact]
verify_jwt = true

[functions.x-trends]
verify_jwt = true

[functions.telegram-accounts]
verify_jwt = true

[functions.telegram-extract]
verify_jwt = true

[functions.telegram-send]
verify_jwt = true

[functions.telegram-groups]
verify_jwt = true

[functions.linkedin-extract]
verify_jwt = true

[functions.linkedin-send]
verify_jwt = true

[functions.email-send]
verify_jwt = true

[functions.b2b-extract]
verify_jwt = true
